# Description.
model_template_id: Custom_Instance_Segmentation_MaskRCNN-ResNet50
name: MaskRCNN-ResNet50
task_type: COUNTING
task_family: VISION
instantiation: "CLASS"
summary: MaskRCNN with ResNet50 backbone.
application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTrainingTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask
  nncf: mmdet.apis.ote.apis.detection.OTEDetectionNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdet/apis/ote/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.01
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# EUGENE: WIP
# Stats.
gigaflops: 533.8
size: 177.9
