# Description.
model_template_id: Custom_Object_Detection_Gen3_SSD
name: SSD
task_type: DETECTION
task_family: VISION
instantiation: "CLASS"
summary: Model with fastest inference speed and training time. Works better on simple datasets with large and 
  distinguishable objects.
application:
  ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTrainingTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask
  nncf: mmdet.apis.ote.apis.detection.OTEDetectionNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdet/apis/ote/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 10
      learning_rate:
        default_value: 0.01
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 9.4
size: 7.6
